// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice =
  | NosotrosSlice
  | ContactoSlice
  | ServiciosSlice
  | TestimoniesSlice
  | MisionSlice
  | MarqueeSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings → Nav Item*
 */
export interface SettingsDocumentDataNavItemItem {
  /**
   * Item Link field in *Settings → Nav Item*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_item[].item_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  item_link: prismic.LinkField;

  /**
   * Link Label field in *Settings → Nav Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_item[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Nav Item field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_item: prismic.GroupField<Simplify<SettingsDocumentDataNavItemItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument | SettingsDocument;

/**
 * Primary content in *Contacto → Default → Primary*
 */
export interface ContactoSliceDefaultPrimary {
  /**
   * Title field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * CTA Label field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Form Name field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.form_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_name: prismic.KeyTextField;

  /**
   * Form Number field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.form_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_number: prismic.KeyTextField;

  /**
   * Form Email field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.form_email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_email: prismic.KeyTextField;

  /**
   * Form Consulta field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.form_consulta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  form_consulta: prismic.KeyTextField;
}

/**
 * Default variation for Contacto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contacto*
 */
type ContactoSliceVariation = ContactoSliceDefault;

/**
 * Contacto Shared Slice
 *
 * - **API ID**: `contacto`
 * - **Description**: Contacto
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactoSlice = prismic.SharedSlice<
  "contacto",
  ContactoSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hook1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hook
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hook: prismic.KeyTextField;

  /**
   * Hook2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hook2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hook2: prismic.KeyTextField;

  /**
   * CTA Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Marquee → Default → Primary*
 */
export interface MarqueeSliceDefaultPrimary {
  /**
   * Slogan1 field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.slogan1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slogan1: prismic.KeyTextField;

  /**
   * Slogan2 field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.slogan2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slogan2: prismic.KeyTextField;

  /**
   * Slogan3 field in *Marquee → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marquee.default.primary.slogan3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  slogan3: prismic.KeyTextField;
}

/**
 * Default variation for Marquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marquee*
 */
type MarqueeSliceVariation = MarqueeSliceDefault;

/**
 * Marquee Shared Slice
 *
 * - **API ID**: `marquee`
 * - **Description**: Marquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MarqueeSlice = prismic.SharedSlice<
  "marquee",
  MarqueeSliceVariation
>;

/**
 * Primary content in *Mision → Default → Primary*
 */
export interface MisionSliceDefaultPrimary {
  /**
   * Title field in *Mision → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mision.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Mision → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: mision.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Mision → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mision.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Mision Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MisionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MisionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Mision*
 */
type MisionSliceVariation = MisionSliceDefault;

/**
 * Mision Shared Slice
 *
 * - **API ID**: `mision`
 * - **Description**: Mision
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MisionSlice = prismic.SharedSlice<"mision", MisionSliceVariation>;

/**
 * Primary content in *Nosotros → Default → Primary*
 */
export interface NosotrosSliceDefaultPrimary {
  /**
   * Title field in *Nosotros → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descripcion field in *Nosotros → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.default.primary.descripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcion: prismic.RichTextField;

  /**
   * Image field in *Nosotros → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nosotros.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Nosotros Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NosotrosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NosotrosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Nosotros*
 */
type NosotrosSliceVariation = NosotrosSliceDefault;

/**
 * Nosotros Shared Slice
 *
 * - **API ID**: `nosotros`
 * - **Description**: Nosotros
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NosotrosSlice = prismic.SharedSlice<
  "nosotros",
  NosotrosSliceVariation
>;

/**
 * Item in *Servicios → Default → Primary → Item*
 */
export interface ServiciosSliceDefaultPrimaryItemItem {
  /**
   * Image field in *Servicios → Default → Primary → Item*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.item[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Servicio field in *Servicios → Default → Primary → Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.item[].servicio
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  servicio: prismic.KeyTextField;

  /**
   * Descripcion field in *Servicios → Default → Primary → Item*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.item[].descripcion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descripcion: prismic.RichTextField;
}

/**
 * Primary content in *Servicios → Default → Primary*
 */
export interface ServiciosSliceDefaultPrimary {
  /**
   * Title field in *Servicios → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Item field in *Servicios → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.item[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  item: prismic.GroupField<Simplify<ServiciosSliceDefaultPrimaryItemItem>>;
}

/**
 * Default variation for Servicios Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiciosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiciosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Servicios*
 */
type ServiciosSliceVariation = ServiciosSliceDefault;

/**
 * Servicios Shared Slice
 *
 * - **API ID**: `servicios`
 * - **Description**: Servicios
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiciosSlice = prismic.SharedSlice<
  "servicios",
  ServiciosSliceVariation
>;

/**
 * Item in *Testimonies → Default → Primary → Card*
 */
export interface TestimoniesSliceDefaultPrimaryCardItem {
  /**
   * Name field in *Testimonies → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.default.primary.card[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Image field in *Testimonies → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.default.primary.card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Comment field in *Testimonies → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.default.primary.card[].comment
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  comment: prismic.RichTextField;

  /**
   * calificacion field in *Testimonies → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.default.primary.card[].calificacion
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  calificacion: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonies → Default → Primary*
 */
export interface TestimoniesSliceDefaultPrimary {
  /**
   * Title field in *Testimonies → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Card field in *Testimonies → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<TestimoniesSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for Testimonies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimoniesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonies*
 */
type TestimoniesSliceVariation = TestimoniesSliceDefault;

/**
 * Testimonies Shared Slice
 *
 * - **API ID**: `testimonies`
 * - **Description**: Testimonies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesSlice = prismic.SharedSlice<
  "testimonies",
  TestimoniesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavItemItem,
      AllDocumentTypes,
      ContactoSlice,
      ContactoSliceDefaultPrimary,
      ContactoSliceVariation,
      ContactoSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MarqueeSlice,
      MarqueeSliceDefaultPrimary,
      MarqueeSliceVariation,
      MarqueeSliceDefault,
      MisionSlice,
      MisionSliceDefaultPrimary,
      MisionSliceVariation,
      MisionSliceDefault,
      NosotrosSlice,
      NosotrosSliceDefaultPrimary,
      NosotrosSliceVariation,
      NosotrosSliceDefault,
      ServiciosSlice,
      ServiciosSliceDefaultPrimaryItemItem,
      ServiciosSliceDefaultPrimary,
      ServiciosSliceVariation,
      ServiciosSliceDefault,
      TestimoniesSlice,
      TestimoniesSliceDefaultPrimaryCardItem,
      TestimoniesSliceDefaultPrimary,
      TestimoniesSliceVariation,
      TestimoniesSliceDefault,
    };
  }
}
