// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contacto: dynamic(() => import("./Contacto")),
  hero: dynamic(() => import("./Hero")),
  marquee: dynamic(() => import("./Marquee")),
  mision: dynamic(() => import("./Mision")),
  servicios: dynamic(() => import("./Servicios")),
  testimonies: dynamic(() => import("./Testimonies")),
};
